HOST = "127.0.0.1"
PORT = 9092
BUFFER_SIZE = 1024

PROTOCOL_VERSION = 1

MESSAGE_TYPE_PUBLISH = "PUBLISH"
MESSAGE_TYPE_CONSUME = "CONSUME"
MESSAGE_TYPE_ACK = "ACK"
MESSAGE_TYPE_REGISTER = "REGISTER"
MESSAGE_TYPE_HEARTBEAT = "HEARTBEAT"

STATUS_SUCCESS = "SUCCESS"